name: Golangci-Lint Check

on:
  push:
    branches:
      - "master"
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-matrix
        run: |
          # Determine the base and head commits for diff based on the event type
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            BASE_SHA="${{ github.event.pull_request.base.sha }}"
            HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          else
            BASE_SHA="${{ github.event.before }}"
            HEAD_SHA="${{ github.event.after }}"
          fi

          # Extract directories from changed files
          FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
          DIRECTORIES=$(echo "$FILES" | xargs -L1 dirname | sort -u | grep -vE '/\.')

          # Check each directory for a go.mod file and prepare JSON array
          GO_MOD_DIRECTORIES=()
          for dir in $DIRECTORIES; do
            if [[ -f "$dir/go.mod" ]]; then
              GO_MOD_DIRECTORIES+=("$dir")
            fi
          done
          JSON_ARRAY=$(printf '%s\n' "${GO_MOD_DIRECTORIES[@]}" | jq -R -s -c 'split("\n")[:-1]')
          
          # Export the JSON array
          echo "matrix=${JSON_ARRAY}" >> $GITHUB_OUTPUT

  lint:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--tests=false --timeout=5m"
          workdir: ${{ matrix.modules }}
          fail_on_error: true
          filter_mode: nofilter
