name: Gosec Security Scan

on:
  push:
    branches:
      - "master"
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-matrix
        run: |
          # Determine the base and head commits for diff based on the event type
          BASE_SHA="${{ github.event.pull_request.base.sha || github.event.before }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha || github.event.after }}"

          # Extract directories from changed files, only include those with go.mod files
          GO_MOD_DIRECTORIES=()
          FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -vE '/\.')
          DIRECTORIES=$(echo "$FILES" | xargs -L1 dirname | sort -u)

          for dir in $DIRECTORIES; do
            if [[ -f "$dir/go.mod" ]]; then
              GO_MOD_DIRECTORIES+=("$dir")
            fi
          done

          # Export the JSON array
          JSON_ARRAY=$(printf '%s\n' "${GO_MOD_DIRECTORIES[@]}" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${JSON_ARRAY}" >> $GITHUB_OUTPUT

  gosec-scan:
    runs-on: ubuntu-latest
    needs: generate-matrix
    env:
      GO111MODULE: on
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.x'
          check-latest: true
          cache: false
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run gosec
        working-directory: ${{ matrix.modules }}
        run: gosec ./...
