name: Gosec Security Scan

on:
  push:
    branches:
      - "master"
      - "main"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - LICENSE
      - ".github/ISSUE_TEMPLATE/*.yml"
      - ".github/dependabot.yml"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
            go_mod_dirs=""
            for file in $changed_files; do
              dir=$(dirname "$file")
              if [[ -f "$dir/go.mod" ]]; then
                go_mod_dirs+="$dir "
              fi
            done
            go_mod_dirs=$(echo "$go_mod_dirs" | tr ' ' '\n' | sort -u | awk 'NF' | tr '\n' ' ')
          else
            go_mod_dirs=$(find . -name go.mod -exec dirname {} \; | sort -u | awk 'NF' | tr '\n' ' ')
          fi

          # Export the JSON array
          JSON_ARRAY=$(printf '%s\n' "$go_mod_dirs" | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=${JSON_ARRAY}" >> $GITHUB_OUTPUT

  gosec-scan:
    runs-on: ubuntu-latest
    needs: generate-matrix
    env:
      GO111MODULE: on
    strategy:
      matrix:
        modules: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.x'
          check-latest: true
          cache: false
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run gosec
        working-directory: ${{ matrix.modules }}
        run: gosec ./...
