name: Run CloudflareKV Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: JarvusInnovations/background-action@v1
        name: Bootstrap System Under Test (SUT)
        with:
          run: .github/scripts/initialize-wrangler.sh

          wait-on: |
            http://localhost:8787            

      - name: Go to cloudflarekv directory
        run: cd cloudflarekv

      - name: Run Go Tests
        run: go test
