name: Tests CloudflareKV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          go-version:
              - 1.21.x
              - 1.22.x

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }} 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: JarvusInnovations/background-action@v1
        name: Bootstrap System Under Test (SUT)
        with:
          run: |
            .github/scripts/initialize-wrangler.sh
            npx wrangler dev

          wait-on: |
            http://localhost:8787/health           

      - name: Go to cloudflarekv directory
        run: cd cloudflarekv

      - name: Run Go Tests
        run: go test
