on:
    push:
        branches:
            - master
            - main
        paths:
            - 'nats/**'
    pull_request:
        paths:
            - 'nats/**'
name: "Tests Local Storage"
jobs:
    Tests:
        strategy:
            matrix:
                go-version:
                    - 1.21.x
        runs-on: ubuntu-latest
        steps:
            -   name: Fetch Repository
                uses: actions/checkout@v4
            -   name: Install Go
                uses: actions/setup-go@v5
                with:
                    go-version: '${{ matrix.go-version }}'
            -   name: Run NATS
                run: |
                    docker run -d --name nats-jetstream -p 4222:4222 nats:latest -- --jetstream
                    sleep 2
            -   name: Test Nats
                run: cd ./nats && go test ./... -v -race
